name: bug report.
description: Отчёт о дефекте.
title: "[Ошибка]: "
labels: ["bug"]
body:
 - type: textarea
   id: bugLabel
   attributes:
    label: Название дефекта.
    description: DescriptionsOfBug
    placeholder: Описание дефекта и его возникновение.
   validations:
    required: true #поле обязательно для заполнения

 - type: textarea
   id: expectation
   attributes:
    label: Ожидаемый результат.
    description: ExpectedResult
    placeholder: Описание ожидаемого результата.
   validations:
    required: true #поле обязательно для заполнения

 - type: textarea
   id: reality
   attributes:
    label: Фактический результат.
    description: TheActualResult
    placeholder: Описание происходящего.
   validations:
    required: true #поле обязательно для заполнения
 
 - type: dropdown
   id: Priority
   attributes:
    label: Приоритет дефекта.
    description: Выберите приоритет дефекта
    options:
     - Низкий
     - Средний
     - Высокий
   validations:
    required: true

 - type: dropdown
   id: Seriousness
   attributes:
    label: Серьёзность дефекта.
    description: Выберите серьёзность дефекта.
    options:
     - Низкая 
     - Средняя 
     - Высокая 
     - Критическая 
   validations:
    required: true
 
 - type: checkboxes
   id: checkBoxLabel
   attributes:
    label: Ошибка привела к вылету приложения?
    description: Закрывается ли приложение после возникновения ошибки?
    options:
    - label: Да
    - label: Нет
      required: true #флажок обязателен или нет

 - type: textarea
   id: additionally
   attributes:
    label: Вложения(Логи/Скриншоты)
    description: Attachments
    placeholder: Если есть, вставьте сюда
   validations:
    required: true #поле обязательно для заполнения
