name: bug report
description: Отчёт о дефекте
title: "[Ошибка]: "
labels: ["bug"]
body:
 - type: textarea
   id: bugLabel
   attributes:
    label: Название дефекта
    description: descriptionsOfBug
    placeholder: Описание возникновения дефекта
   validations:
     required: true #поле обязательно для заполнения
 
 - type: dropdown
   id: Priority
   attributes:
    label: Приоритет дефекта
    description: Выбирите приоритет дефекта
    options:
     - Низкий
     - Средний
     - Высокий
   validations:
    required: true

     - type: dropdown
       id: Seriousness
       attributes:
        label: Серьёзность дефекта
        description: Выбирите серьёзность дефекта
        options:
         - Низкая 
         - Средняя 
         - Высокая 
         - Критическая 
       validations:
        required: true
 
 - type: checkboxes
   id: checkBoxLabel
   attributes:
    label: Ошибка привела к вылету приложения?
    description: Закрывается ли приложение после возникновения ошибки?
    options:
    - label: Да
    - label: Нет
      required: true #флажок обязателен или нет
