name: bug report
description: Отчёт о дефекте
title: "[Ошибка]: "
labels: ["bug"]
body:
 - type: textarea
   id: bugLabel
   attributes:
    label: Название дефекта
    description: descriptionBug
    placeholder: Описание возникновения дефекта
   validations:
     required: true #поле обязательно для заполнения
 
 - type: dropdown
   id: dropBoxLabel
   attributes:
    label: Приоритет дефекта
    description: Выбирите приоритет дефекта
    options:
     - Низкий
     - Средний
     - Высокий
   validations:
    required: true
  
 - type: markdown
   attributes:
   value: |
   
 - type: checkboxes
   id: checkBoxLabel
   attributes:
    label: Вылет приложения
    description: Ошибка привела к вылету приложения?
    options:
    - label: Да
      required: true #флажок обязателен или нет
